### PR TITLE
Add me!

### PR DESCRIPTION
**Pull request by sedouard**

### CODE REVIEW

**Comment by sedouard** [comment]
😂😂😂

**Comment by ritazh** [comment]
screen shot 2016-11-10 at 8 31 00 pm

**Comment by ritazh** [comment]
😃 😃 😃 
screen shot 2016-11-10 at 8 33 21 pm

**Comment by sedouard** [comment]
lol where did the email come from?

**Comment by ritazh** [comment]
I made it up :)

**Pull request merged**
